name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
        platform: [linux/x86_64, linux/arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Install Gcc
        if: matrix.arch == 'aarch64'
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu
          echo "export CC_aarch64-unknown-linux-musl=aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - run: |
          rustup toolchain install stable --profile minimal
          rustup target add ${{ matrix.arch }}-unknown-linux-musl

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ matrix.arch }}

      - name: Build
        run: |
          cargo build --release --target ${{ matrix.arch }}-unknown-linux-musl
          mkdir ./dist
          cp target/${{ matrix.arch }}-unknown-linux-musl/release/rust-multiarch ./dist/rust-multiarch

      - name: Smoke Test
        run: |
          docker build -t --platform ${{ matrix.platform }} rust-multiarch .
          docker run --rm --platform ${{ matrix.platform }} rust-multiarch
